on:
  workflow_dispatch:
      inputs:
      only:
        description: 'Specific image name to build'
        type: string
        required: true
jobs:
  build-0:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      actions: read
    steps:

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.3.*'
          terraform_wrapper: false

      - name: Terraform apply
        env:
          TF_VAR_target_repository: cgr.dev/chainguard
          TF_APKO_DISABLE_VERSION_TAGS: true  # Disable creating new version tags.
        run: |
          set -x -o pipefail
          env | grep '^TF_VAR_'

          echo ::group::terraform init
          terraform init
          echo ::endgroup::
          terraform apply -auto-approve "-target=module.${{ inputs.only }}"

